feat: Extracting `state_sync_timeout` into the config (#3887)
* feat: Extracting `state_sync_timeout` into the config

State sync timeout is the time we wait after sending a request during
state sync before we resend it. It historically used to be 10 seconds,
which was inadequate for the production environment, so it was bumped to
60s. This, in turn, became inadequate for tests, in particular stres.py
started failing in modes in which messages can be dropped.
In this change I'm extracting it into a config variable.

Test plan
---------
stress.py passed more frequently (some failures are still present):
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1068

* Fixing test compilation errors