integration-tests: fix test assuming block heights don’t skip numbers (#6059)
The chunks_produced_and_distributed_common function (used by all the
tests in chunks_management.rs) assumes that previous block’s height is
one less than the height of the current block:

    check_height(*block.header().prev_hash(), block.header().height() - 1);

This isn’t true in general so remove that assumption.

This fixes following assert failures:

    thread 'tests::client::chunks_management::chunks_recovered_from_full_timeout_too_short' panicked at 'assertion failed: `(left == right)`
      left: `2`,
     right: `3`', integration-tests/src/tests/client/chunks_management.rs:46:13