fix: add missing chrono feature (#11704)
My local build fails with the following error:
```
> cargo test -p near-chain --no-run 
   Compiling near-chain-configs v0.0.0 (/Users/pugachag/Projects/near/nearcore/core/chain-configs)
   Compiling near-vm-runner v0.0.0 (/Users/pugachag/Projects/near/nearcore/runtime/near-vm-runner)
error[E0599]: no function or associated item named `now` found for struct `Utc` in the current scope
   --> core/chain-configs/src/test_genesis.rs:282:40
    |
282 |             let default = chrono::Utc::now();
    |                                        ^^^ function or associated item not found in `Utc`

```

`Utc::now()` is only available with `clock` feature.